import 'package:get/get.dart';

class LocalStrings extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'All': 'All',
          'Vanchan': 'Vanchan',
          'Mala jap': 'Mala Jap',
          'Home': 'Home',
          'Language': 'Language',
          'Refer a friend': 'Refer a friend',
          'Rate Us': 'Rate Us',
          'Sign Out': 'Sign Out',
          'English': 'English',
          'Gujarati': 'Gujarati',
          'Cancel': 'Cancel',
          'Done': 'Done',
          'Search PDF by Name': 'Search Book by Name',
          'Swaminarayan': 'Swaminarayan',
          'User Data List': 'Members',
          'Upload PDF': 'Manage Books',
          'Upload Book': 'Upload Book',
          'Select Language': 'Select Language',
          'No PDF found': 'No Book found',
          'Go to MalaJap': 'Go to MalaJap',
          'Go to Vanchan': 'Go to Vanchan',
          'Welcome': 'Welcome',
          'Profile': 'Profile',
          'Book Content': 'Book Content',
          'Book Name': 'Book Name',
          'Credit Score': 'Today\'s Mala Jap 📿 : ',
          'PDF Description': 'Book Description',
          'Click here to upload PDF Photo': 'Click here to upload book photo',
          'Click here to upload PDF': 'Click here to upload book',
          'Select PDF language': 'Select book language',
          'Are you sure you want to sign out?': 'Are you sure you want to sign out?',
          'Yes': 'Yes',
          'No': 'No',
          'Last Month': 'Last Month',
          'Last Week': 'Last Week',
          'Date': 'Date',
          'Credits': 'Mala Jap',
          'Mobile No': 'Mobile No',
          'Total Credits': 'Total Mala Jap',
          'Village': 'Village',
          'Are you sure want to delete book?': 'Are you sure want to delete book?',
          'Delete Book': 'Delete Book',
          'Okay': 'Okay',
          'Congratulation': 'Congratulation',
          'Download Excel': 'Download Excel',
          'Jay Shree Swaminarayan Your Mala hasp completed.': 'Jay Shree Swaminarayan Your Mala has completed.',
        },
        'hi_IN': {
          'All': 'તમામ',
          'Vanchan': 'વાંચન',
          'Mala Jap': 'માળા જાપ',
          'Home': 'ઘર',
          'Language': 'ભાષા',
          'Refer a friend': 'મિત્ર નો સંદર્ભ લો',
          'Rate Us': 'રેટ કરો',
          'Sign Out': 'સાઇન આઉટ કરો',
          'English': 'અંગ્રેજી',
          'Gujarati': 'ગુજરાતી',
          'Cancel': 'રદ કરો',
          'Done': 'પસંદ કરો',
          'Search PDF by Name': 'નામ દ્વારા પુસ્તક શોધો',
          'Swaminarayan': 'સ્વામિનારાયણ',
          'Select Language': 'ભાષા પસંદ કરો',
          'Upload PDF': 'પુસ્તકોનું સંચાલન કરો',
          'User Data List': 'સભ્ય યાદી',
          'No PDF found': 'કોઈ પુસ્તક મળ્યું નથી',
          'Go to MalaJap': 'માળાજાપ પર જાઓ',
          'Go to Vanchan': 'વાંચન પર જાઓ',
          'Welcome': 'સુસ્વાગતમ્',
          'Profile': 'પ્રોફાઇલ',
          'Book Content': 'પુસ્તક વિસ્તાર',
          'Book Name': 'પુસ્તકનું નામ',
          'Credit Score': 'આજની માળા જાપ 📿 :',
          'PDF Description': 'પુસ્તકનું વર્ણન',
          'Select PDF language': 'પુસ્તક ની ભાષા પસંદ કરો ',
          'Click here to upload PDF Photo': 'પુસ્તક ફોટો અપલોડ કરવા માટે અહીં ક્લિક કરો ',
          'Click here to upload PDF': 'પુસ્તક અપલોડ કરવા માટે અહીં ક્લિક કરો',
          'Are you sure you want to sign out?': 'શું તમે ખરેખર સાઇન આઉટ કરવા માંગો છો? ',
          'Okay': 'ઠીક છે',
          'Yes': 'હા',
          'No': 'ના',
          'Last Month': 'છેલ્લા મહિને',
          'Last Week': 'છેલ્લા સપ્તાહે',
          'Date': ' તારીખ',
          'Upload Book': 'પુસ્તક અપલોડ કરો',
          'Credits': 'માળા જાપ',
          'Mobile No': 'મોબાઇલ',
          'Total Credits': 'કુલ માળા',
          'Village': 'ગામ',
          'Download Excel': 'એક્સેલ ડાઉનલોડ કરો',
          'Congratulation': 'અભિનંદન',
          'Are you sure want to delete book?': 'શું તમે ખરેખર પુસ્તક કાઢી નાખવા માંગો છો?',
          'Delete Book': 'પુસ્તક કાઢી નાખો',
          'Jay Shree Swaminarayan Your Mala hasp completed.': 'જય શ્રી સ્વામિનારાયણ તમારો જાપ પૂર્ણ થયો.',
        }
      };
}
